/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mão.na.roda;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno_Manha
 */
public class Tela extends javax.swing.JFrame {


    public static CarroController cCarro = new CarroController();
    public static AluguelController cAluguel = new AluguelController();
    public static AgendamentoController cAgendamento = new AgendamentoController();
    public static VendaController cVenda = new VendaController();
    public static Usuario cliente;
    Funcionalidades event = new Funcionalidades();

    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        p_2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        l_nome = new javax.swing.JLabel();
        c_nome = new javax.swing.JTextField();
        l_email = new javax.swing.JLabel();
        c_email = new javax.swing.JTextField();
        l_idade = new javax.swing.JLabel();
        c_idade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        l_celular = new javax.swing.JLabel();
        c_dd = new javax.swing.JTextField();
        c_celular = new javax.swing.JTextField();
        l_cnh = new javax.swing.JLabel();
        c_cnh = new javax.swing.JTextField();
        btn_enviar = new javax.swing.JButton();
        btn_administrador = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        s_categoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 465));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_1.setBackground(new java.awt.Color(27, 29, 32));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mão na roda");

        javax.swing.GroupLayout p_1Layout = new javax.swing.GroupLayout(p_1);
        p_1.setLayout(p_1Layout);
        p_1Layout.setHorizontalGroup(
            p_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_1Layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(126, 126, 126))
        );
        p_1Layout.setVerticalGroup(
            p_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(p_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        p_2.setBackground(new java.awt.Color(232, 241, 242));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Preencha o formulário abaixo para ter acesso ao sistema:");

        l_nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l_nome.setText("Nome completo:");

        c_nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        l_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l_email.setText("Email:");

        c_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        l_idade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l_idade.setText("Idade:");

        c_idade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("anos");

        l_celular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l_celular.setText("Celular:");

        c_dd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        c_dd.setToolTipText("");

        c_celular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        l_cnh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l_cnh.setText("CNH:");

        c_cnh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_enviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_enviar.setText("Enviar");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });

        btn_administrador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_administrador.setText("Administrador");
        btn_administrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_administradorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Categoria:");

        s_categoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "A", "B", "C", "D", "E" }));

        javax.swing.GroupLayout p_2Layout = new javax.swing.GroupLayout(p_2);
        p_2.setLayout(p_2Layout);
        p_2Layout.setHorizontalGroup(
            p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_2Layout.createSequentialGroup()
                .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_2Layout.createSequentialGroup()
                                .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(l_email)
                                    .addComponent(l_nome)
                                    .addComponent(l_idade)
                                    .addComponent(l_celular)
                                    .addComponent(l_cnh))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c_nome)
                                    .addComponent(c_email)
                                    .addGroup(p_2Layout.createSequentialGroup()
                                        .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(p_2Layout.createSequentialGroup()
                                                .addComponent(c_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(p_2Layout.createSequentialGroup()
                                                .addComponent(c_dd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(c_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(p_2Layout.createSequentialGroup()
                                        .addComponent(c_cnh, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(s_categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_enviar)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_administrador)))
                .addContainerGap())
        );
        p_2Layout.setVerticalGroup(
            p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_nome)
                    .addComponent(c_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_email)
                    .addComponent(c_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_idade)
                    .addComponent(c_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_celular)
                    .addComponent(c_dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_cnh)
                    .addComponent(c_cnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(s_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_enviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btn_administrador)
                .addGap(31, 31, 31))
        );

        getContentPane().add(p_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        VendaController vendas = new VendaController();
        
        vendas.getVenda(0);
    }//GEN-LAST:event_formWindowOpened

    private void btn_administradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_administradorActionPerformed
        event.mudaTela(new Tela_ADM(), this);
    }//GEN-LAST:event_btn_administradorActionPerformed

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed

        String categoria = s_categoria.getSelectedItem().toString();

        try {
            if (categoria.equals("B")) {
                cliente = new Usuario(c_nome.getText(), c_email.getText(), Integer.parseInt(c_idade.getText()), Integer.parseInt(c_dd.getText()), c_celular.getText(), c_cnh.getText());
                cliente.verificaIdade(Integer.parseInt(c_idade.getText()));
                event.mudaTela(new Home(), this);
            } else {
                JOptionPane.showMessageDialog(
                    null,
                    "Desculpe, nosso sitema é feito apenas para pessoa com categoria de CNH: B!",
                    "Erro",
                    JOptionPane.INFORMATION_MESSAGE);

                c_nome.setText("");
                c_email.setText("");
                c_idade.setText("");
                c_dd.setText("");
                c_celular.setText("");
                c_cnh.setText("");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                null,
                "Dados inseridos incorretamente!",
                "Erro",
                JOptionPane.ERROR_MESSAGE);

            c_nome.setText("");
            c_email.setText("");
            c_idade.setText("");
            c_dd.setText("");
            c_celular.setText("");
            c_cnh.setText("");
        }

    }//GEN-LAST:event_btn_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_administrador;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JTextField c_celular;
    private javax.swing.JTextField c_cnh;
    private javax.swing.JTextField c_dd;
    private javax.swing.JTextField c_email;
    private javax.swing.JTextField c_idade;
    private javax.swing.JTextField c_nome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel l_celular;
    private javax.swing.JLabel l_cnh;
    private javax.swing.JLabel l_email;
    private javax.swing.JLabel l_idade;
    private javax.swing.JLabel l_nome;
    private javax.swing.JPanel p_1;
    private javax.swing.JPanel p_2;
    private javax.swing.JComboBox<String> s_categoria;
    // End of variables declaration//GEN-END:variables
}
