/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mão.na.roda;

/**
 *
 * @author Italo
 */
public class Tela_ADM extends javax.swing.JFrame {
    
    Funcionalidades event = new Funcionalidades();

    /**
     * Creates new form Tela_ADM
     */
    public Tela_ADM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        p_2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        l_usuario = new javax.swing.JLabel();
        c_usuario = new javax.swing.JTextField();
        btn_enviarAdm = new javax.swing.JButton();
        btn_administrador = new javax.swing.JButton();
        l_senha = new javax.swing.JLabel();
        c_senha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_1.setBackground(new java.awt.Color(27, 29, 32));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mão na roda - Admin");

        javax.swing.GroupLayout p_1Layout = new javax.swing.GroupLayout(p_1);
        p_1.setLayout(p_1Layout);
        p_1Layout.setHorizontalGroup(
            p_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_1Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(71, 71, 71))
        );
        p_1Layout.setVerticalGroup(
            p_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(p_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        p_2.setBackground(new java.awt.Color(232, 241, 242));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Login");

        l_usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l_usuario.setText("Usuário:");

        c_usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_enviarAdm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_enviarAdm.setText("Enviar");
        btn_enviarAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarAdmActionPerformed(evt);
            }
        });

        btn_administrador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_administrador.setText("Voltar");
        btn_administrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_administradorActionPerformed(evt);
            }
        });

        l_senha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l_senha.setText("Senha:");

        c_senha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout p_2Layout = new javax.swing.GroupLayout(p_2);
        p_2.setLayout(p_2Layout);
        p_2Layout.setHorizontalGroup(
            p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_2Layout.createSequentialGroup()
                .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(p_2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(l_senha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(l_usuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(c_usuario)
                            .addComponent(c_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p_2Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btn_enviarAdm)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_2Layout.createSequentialGroup()
                        .addComponent(btn_administrador)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(152, 152, 152))))
        );
        p_2Layout.setVerticalGroup(
            p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_usuario)
                    .addComponent(c_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_senha)
                    .addComponent(c_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_enviarAdm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(btn_administrador)
                .addContainerGap())
        );

        getContentPane().add(p_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enviarAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarAdmActionPerformed
        Administrador adm = new Administrador("Admin", "admin@admin.com", 19, 31, "998951631");
        
        if(adm.verificaAdministrador(c_usuario.getText(), c_senha.getText())){
            event.mudaTela(new Home_ADM(), this);
        }
    }//GEN-LAST:event_btn_enviarAdmActionPerformed

    private void btn_administradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_administradorActionPerformed
        event.mudaTela(new Tela(), this);
    }//GEN-LAST:event_btn_administradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_ADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_ADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_ADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_ADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_ADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_administrador;
    private javax.swing.JButton btn_enviarAdm;
    private javax.swing.JPasswordField c_senha;
    private javax.swing.JTextField c_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l_senha;
    private javax.swing.JLabel l_usuario;
    private javax.swing.JPanel p_1;
    private javax.swing.JPanel p_2;
    // End of variables declaration//GEN-END:variables
}
